### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by rcubed1003** [asciidude/CSLMessageLogger#8]
TypeError: Cannot read properties of null (reading 'id')
    at Client.<anonymous> (C:\Users\ \Desktop\CSLMessageLogger-main\index.js:35:86)
    at Client.emit (node:events:513:28)
    at MessageCreateAction.handle (C:\Users\\Desktop\CSLMessageLogger-main\node_modules\discord.js-selfbot-v13\src\client\actions\MessageCreate.js:30:14)
    at module.exports [as MESSAGE_CREATE] (C:\Users\\Desktop\CSLMessageLogger-main\node_modules\discord.js-selfbot-v13\src\client\websocket\handlers\MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (C:\Users\\Desktop\CSLMessageLogger-main\node_modules\discord.js-selfbot-v13\src\client\websocket\WebSocketManager.js:359:31)
    at WebSocketShard.onPacket (C:\Users\\Desktop\CSLMessageLogger-main\node_modules\discord.js-selfbot-v13\src\client\websocket\WebSocketShard.js:489:22)
    at WebSocketShard.onMessage (C:\Users\\Desktop\CSLMessageLogger-main\node_modules\discord.js-selfbot-v13\src\client\websocket\WebSocketShard.js:324:10)
    at WebSocket.onMessage (C:\Users\\Desktop\CSLMessageLogger-main\node_modules\ws\lib\event-target.js:199:18)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (C:\Users\\Desktop\CSLMessageLogger-main\node_modules\ws\lib\websocket.js:1178:20)

Node.js v18.13.0

**Comment by asciidude** [comment]
I see the issue here. I'll try to fix it when I get home, if I remember.

**Comment by asciidude** [comment]
Sorry, forgot about this. Just pushed a fix out for it.
