### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by Yqno** [asciidude/CSLMessageLogger#9]
TypeError: Cannot read properties of null (reading 'id')
    at Client.<anonymous> (/home/urahara/CSLMessageLogger/index.js:37:61)
    at Client.emit (node:events:512:28)
    at MessageCreateAction.handle (/home/urahara/CSLMessageLogger/node_modules/discord.js-selfbot-v13/src/client/actions/MessageCreate.js:30:14)
    at module.exports [as MESSAGE_CREATE] (/home/urahara/CSLMessageLogger/node_modules/discord.js-selfbot-v13/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/urahara/CSLMessageLogger/node_modules/discord.js-selfbot-v13/src/client/websocket/WebSocketManager.js:359:31)
    at WebSocketShard.onPacket (/home/urahara/CSLMessageLogger/node_modules/discord.js-selfbot-v13/src/client/websocket/WebSocketShard.js:489:22)
    at WebSocketShard.onMessage (/home/urahara/CSLMessageLogger/node_modules/discord.js-selfbot-v13/src/client/websocket/WebSocketShard.js:324:10)
    at WebSocket.onMessage (/home/urahara/CSLMessageLogger/node_modules/ws/lib/event-target.js:199:18)
    at WebSocket.emit (node:events:512:28)
    at Receiver.receiverOnMessage (/home/urahara/CSLMessageLogger/node_modules/ws/lib/websocket.js:1178:20)

Node.js v19.8.1

**Comment by MichaelDavidGK** [comment]
Check #10

**Comment by asciidude** [comment]
Resolved with Michael's fix
